<?php
/**
 * EventsApi
 * PHP version 5
 *
 * @category Class
 * @package  SignRequest
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SignRequest API
 *
 * API for SignRequest.com
 * OpenAPI spec version: v1
 * Contact: tech-support@signrequest.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.11
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace SignRequest\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use SignRequest\ApiException;
use SignRequest\Configuration;
use SignRequest\HeaderSelector;
use SignRequest\ObjectSerializer;

/**
 * EventsApi Class Doc Comment
 *
 * @category Class
 * @package  SignRequest
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class EventsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation eventsList
     *
     * Retrieve a list of Events
     *
     * @param  string $document__uuid  (optional)
     * @param  string $document__external_id  (optional)
     * @param  string $document__signrequest__who  (optional)
     * @param  string $document__signrequest__from_email  (optional)
     * @param  string $document__status  (optional)
     * @param  string $document__user__email  (optional)
     * @param  string $document__user__first_name  (optional)
     * @param  string $document__user__last_name  (optional)
     * @param  string $delivered  (optional)
     * @param  string $delivered_on  (optional)
     * @param  string $timestamp  (optional)
     * @param  string $status  (optional)
     * @param  string $event_type  (optional)
     * @param  int $page A page number within the paginated result set. (optional)
     * @param  int $limit Number of results to return per page. (optional)
     *
     * @throws \SignRequest\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \SignRequest\Model\InlineResponse2004
     */
    public function eventsList($document__uuid = null, $document__external_id = null, $document__signrequest__who = null, $document__signrequest__from_email = null, $document__status = null, $document__user__email = null, $document__user__first_name = null, $document__user__last_name = null, $delivered = null, $delivered_on = null, $timestamp = null, $status = null, $event_type = null, $page = null, $limit = null)
    {
        list($response) = $this->eventsListWithHttpInfo($document__uuid, $document__external_id, $document__signrequest__who, $document__signrequest__from_email, $document__status, $document__user__email, $document__user__first_name, $document__user__last_name, $delivered, $delivered_on, $timestamp, $status, $event_type, $page, $limit);
        return $response;
    }

    /**
     * Operation eventsListWithHttpInfo
     *
     * Retrieve a list of Events
     *
     * @param  string $document__uuid  (optional)
     * @param  string $document__external_id  (optional)
     * @param  string $document__signrequest__who  (optional)
     * @param  string $document__signrequest__from_email  (optional)
     * @param  string $document__status  (optional)
     * @param  string $document__user__email  (optional)
     * @param  string $document__user__first_name  (optional)
     * @param  string $document__user__last_name  (optional)
     * @param  string $delivered  (optional)
     * @param  string $delivered_on  (optional)
     * @param  string $timestamp  (optional)
     * @param  string $status  (optional)
     * @param  string $event_type  (optional)
     * @param  int $page A page number within the paginated result set. (optional)
     * @param  int $limit Number of results to return per page. (optional)
     *
     * @throws \SignRequest\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \SignRequest\Model\InlineResponse2004, HTTP status code, HTTP response headers (array of strings)
     */
    public function eventsListWithHttpInfo($document__uuid = null, $document__external_id = null, $document__signrequest__who = null, $document__signrequest__from_email = null, $document__status = null, $document__user__email = null, $document__user__first_name = null, $document__user__last_name = null, $delivered = null, $delivered_on = null, $timestamp = null, $status = null, $event_type = null, $page = null, $limit = null)
    {
        $returnType = '\SignRequest\Model\InlineResponse2004';
        $request = $this->eventsListRequest($document__uuid, $document__external_id, $document__signrequest__who, $document__signrequest__from_email, $document__status, $document__user__email, $document__user__first_name, $document__user__last_name, $delivered, $delivered_on, $timestamp, $status, $event_type, $page, $limit);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SignRequest\Model\InlineResponse2004',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation eventsListAsync
     *
     * Retrieve a list of Events
     *
     * @param  string $document__uuid  (optional)
     * @param  string $document__external_id  (optional)
     * @param  string $document__signrequest__who  (optional)
     * @param  string $document__signrequest__from_email  (optional)
     * @param  string $document__status  (optional)
     * @param  string $document__user__email  (optional)
     * @param  string $document__user__first_name  (optional)
     * @param  string $document__user__last_name  (optional)
     * @param  string $delivered  (optional)
     * @param  string $delivered_on  (optional)
     * @param  string $timestamp  (optional)
     * @param  string $status  (optional)
     * @param  string $event_type  (optional)
     * @param  int $page A page number within the paginated result set. (optional)
     * @param  int $limit Number of results to return per page. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function eventsListAsync($document__uuid = null, $document__external_id = null, $document__signrequest__who = null, $document__signrequest__from_email = null, $document__status = null, $document__user__email = null, $document__user__first_name = null, $document__user__last_name = null, $delivered = null, $delivered_on = null, $timestamp = null, $status = null, $event_type = null, $page = null, $limit = null)
    {
        return $this->eventsListAsyncWithHttpInfo($document__uuid, $document__external_id, $document__signrequest__who, $document__signrequest__from_email, $document__status, $document__user__email, $document__user__first_name, $document__user__last_name, $delivered, $delivered_on, $timestamp, $status, $event_type, $page, $limit)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation eventsListAsyncWithHttpInfo
     *
     * Retrieve a list of Events
     *
     * @param  string $document__uuid  (optional)
     * @param  string $document__external_id  (optional)
     * @param  string $document__signrequest__who  (optional)
     * @param  string $document__signrequest__from_email  (optional)
     * @param  string $document__status  (optional)
     * @param  string $document__user__email  (optional)
     * @param  string $document__user__first_name  (optional)
     * @param  string $document__user__last_name  (optional)
     * @param  string $delivered  (optional)
     * @param  string $delivered_on  (optional)
     * @param  string $timestamp  (optional)
     * @param  string $status  (optional)
     * @param  string $event_type  (optional)
     * @param  int $page A page number within the paginated result set. (optional)
     * @param  int $limit Number of results to return per page. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function eventsListAsyncWithHttpInfo($document__uuid = null, $document__external_id = null, $document__signrequest__who = null, $document__signrequest__from_email = null, $document__status = null, $document__user__email = null, $document__user__first_name = null, $document__user__last_name = null, $delivered = null, $delivered_on = null, $timestamp = null, $status = null, $event_type = null, $page = null, $limit = null)
    {
        $returnType = '\SignRequest\Model\InlineResponse2004';
        $request = $this->eventsListRequest($document__uuid, $document__external_id, $document__signrequest__who, $document__signrequest__from_email, $document__status, $document__user__email, $document__user__first_name, $document__user__last_name, $delivered, $delivered_on, $timestamp, $status, $event_type, $page, $limit);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'eventsList'
     *
     * @param  string $document__uuid  (optional)
     * @param  string $document__external_id  (optional)
     * @param  string $document__signrequest__who  (optional)
     * @param  string $document__signrequest__from_email  (optional)
     * @param  string $document__status  (optional)
     * @param  string $document__user__email  (optional)
     * @param  string $document__user__first_name  (optional)
     * @param  string $document__user__last_name  (optional)
     * @param  string $delivered  (optional)
     * @param  string $delivered_on  (optional)
     * @param  string $timestamp  (optional)
     * @param  string $status  (optional)
     * @param  string $event_type  (optional)
     * @param  int $page A page number within the paginated result set. (optional)
     * @param  int $limit Number of results to return per page. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function eventsListRequest($document__uuid = null, $document__external_id = null, $document__signrequest__who = null, $document__signrequest__from_email = null, $document__status = null, $document__user__email = null, $document__user__first_name = null, $document__user__last_name = null, $delivered = null, $delivered_on = null, $timestamp = null, $status = null, $event_type = null, $page = null, $limit = null)
    {

        $resourcePath = '/events/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($document__uuid !== null) {
            $queryParams['document__uuid'] = ObjectSerializer::toQueryValue($document__uuid);
        }
        // query params
        if ($document__external_id !== null) {
            $queryParams['document__external_id'] = ObjectSerializer::toQueryValue($document__external_id);
        }
        // query params
        if ($document__signrequest__who !== null) {
            $queryParams['document__signrequest__who'] = ObjectSerializer::toQueryValue($document__signrequest__who);
        }
        // query params
        if ($document__signrequest__from_email !== null) {
            $queryParams['document__signrequest__from_email'] = ObjectSerializer::toQueryValue($document__signrequest__from_email);
        }
        // query params
        if ($document__status !== null) {
            $queryParams['document__status'] = ObjectSerializer::toQueryValue($document__status);
        }
        // query params
        if ($document__user__email !== null) {
            $queryParams['document__user__email'] = ObjectSerializer::toQueryValue($document__user__email);
        }
        // query params
        if ($document__user__first_name !== null) {
            $queryParams['document__user__first_name'] = ObjectSerializer::toQueryValue($document__user__first_name);
        }
        // query params
        if ($document__user__last_name !== null) {
            $queryParams['document__user__last_name'] = ObjectSerializer::toQueryValue($document__user__last_name);
        }
        // query params
        if ($delivered !== null) {
            $queryParams['delivered'] = ObjectSerializer::toQueryValue($delivered);
        }
        // query params
        if ($delivered_on !== null) {
            $queryParams['delivered_on'] = ObjectSerializer::toQueryValue($delivered_on);
        }
        // query params
        if ($timestamp !== null) {
            $queryParams['timestamp'] = ObjectSerializer::toQueryValue($timestamp);
        }
        // query params
        if ($status !== null) {
            $queryParams['status'] = ObjectSerializer::toQueryValue($status);
        }
        // query params
        if ($event_type !== null) {
            $queryParams['event_type'] = ObjectSerializer::toQueryValue($event_type);
        }
        // query params
        if ($page !== null) {
            $queryParams['page'] = ObjectSerializer::toQueryValue($page);
        }
        // query params
        if ($limit !== null) {
            $queryParams['limit'] = ObjectSerializer::toQueryValue($limit);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation eventsRead
     *
     * Retrieve an Event
     *
     * @param  int $id A unique integer value identifying this event. (required)
     *
     * @throws \SignRequest\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \SignRequest\Model\Event
     */
    public function eventsRead($id)
    {
        list($response) = $this->eventsReadWithHttpInfo($id);
        return $response;
    }

    /**
     * Operation eventsReadWithHttpInfo
     *
     * Retrieve an Event
     *
     * @param  int $id A unique integer value identifying this event. (required)
     *
     * @throws \SignRequest\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \SignRequest\Model\Event, HTTP status code, HTTP response headers (array of strings)
     */
    public function eventsReadWithHttpInfo($id)
    {
        $returnType = '\SignRequest\Model\Event';
        $request = $this->eventsReadRequest($id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SignRequest\Model\Event',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation eventsReadAsync
     *
     * Retrieve an Event
     *
     * @param  int $id A unique integer value identifying this event. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function eventsReadAsync($id)
    {
        return $this->eventsReadAsyncWithHttpInfo($id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation eventsReadAsyncWithHttpInfo
     *
     * Retrieve an Event
     *
     * @param  int $id A unique integer value identifying this event. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function eventsReadAsyncWithHttpInfo($id)
    {
        $returnType = '\SignRequest\Model\Event';
        $request = $this->eventsReadRequest($id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'eventsRead'
     *
     * @param  int $id A unique integer value identifying this event. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function eventsReadRequest($id)
    {
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling eventsRead'
            );
        }

        $resourcePath = '/events/{id}/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
