<?php
/**
 * DocumentTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  SignRequest
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SignRequest API
 *
 * API for SignRequest.com
 *
 * OpenAPI spec version: v1
 * Contact: tech-support@signrequest.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace SignRequest;

/**
 * DocumentTest Class Doc Comment
 *
 * @category    Class */
// * @description Document
/**
 * @package     SignRequest
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DocumentTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Document"
     */
    public function testDocument()
    {
    }

    /**
     * Test attribute "url"
     */
    public function testPropertyUrl()
    {
    }

    /**
     * Test attribute "uuid"
     */
    public function testPropertyUuid()
    {
    }

    /**
     * Test attribute "user"
     */
    public function testPropertyUser()
    {
    }

    /**
     * Test attribute "file_as_pdf"
     */
    public function testPropertyFileAsPdf()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "external_id"
     */
    public function testPropertyExternalId()
    {
    }

    /**
     * Test attribute "frontend_id"
     */
    public function testPropertyFrontendId()
    {
    }

    /**
     * Test attribute "file"
     */
    public function testPropertyFile()
    {
    }

    /**
     * Test attribute "file_from_url"
     */
    public function testPropertyFileFromUrl()
    {
    }

    /**
     * Test attribute "events_callback_url"
     */
    public function testPropertyEventsCallbackUrl()
    {
    }

    /**
     * Test attribute "file_from_content"
     */
    public function testPropertyFileFromContent()
    {
    }

    /**
     * Test attribute "file_from_content_name"
     */
    public function testPropertyFileFromContentName()
    {
    }

    /**
     * Test attribute "template"
     */
    public function testPropertyTemplate()
    {
    }

    /**
     * Test attribute "prefill_tags"
     */
    public function testPropertyPrefillTags()
    {
    }

    /**
     * Test attribute "integrations"
     */
    public function testPropertyIntegrations()
    {
    }

    /**
     * Test attribute "file_from_sf"
     */
    public function testPropertyFileFromSf()
    {
    }

    /**
     * Test attribute "auto_delete_days"
     */
    public function testPropertyAutoDeleteDays()
    {
    }

    /**
     * Test attribute "pdf"
     */
    public function testPropertyPdf()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "api_used"
     */
    public function testPropertyApiUsed()
    {
    }

    /**
     * Test attribute "security_hash"
     */
    public function testPropertySecurityHash()
    {
    }

    /**
     * Test attribute "attachments"
     */
    public function testPropertyAttachments()
    {
    }

    /**
     * Test attribute "auto_delete_after"
     */
    public function testPropertyAutoDeleteAfter()
    {
    }
}
