<?php
/**
 * FileFromSfTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  SignRequest
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SignRequest API
 *
 * API for SignRequest.com
 * OpenAPI spec version: v1
 * Contact: tech-support@signrequest.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.11
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace SignRequest;

/**
 * FileFromSfTest Class Doc Comment
 *
 * @category    Class
 * @description FileFromSf
 * @package     SignRequest
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FileFromSfTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "FileFromSf"
     */
    public function testFileFromSf()
    {
    }

    /**
     * Test attribute "object_type"
     */
    public function testPropertyObjectType()
    {
    }

    /**
     * Test attribute "object_id"
     */
    public function testPropertyObjectId()
    {
    }

    /**
     * Test attribute "uid"
     */
    public function testPropertyUid()
    {
    }
}
