<?php
/**
 * SignerTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  SignRequest
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SignRequest API
 *
 * API for SignRequest.com
 * OpenAPI spec version: v1
 * Contact: tech-support@signrequest.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace SignRequest;

/**
 * SignerTest Class Doc Comment
 *
 * @category    Class
 * @description Signer
 * @package     SignRequest
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SignerTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Signer"
     */
    public function testSigner()
    {
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
    }

    /**
     * Test attribute "display_name"
     */
    public function testPropertyDisplayName()
    {
    }

    /**
     * Test attribute "first_name"
     */
    public function testPropertyFirstName()
    {
    }

    /**
     * Test attribute "last_name"
     */
    public function testPropertyLastName()
    {
    }

    /**
     * Test attribute "email_viewed"
     */
    public function testPropertyEmailViewed()
    {
    }

    /**
     * Test attribute "viewed"
     */
    public function testPropertyViewed()
    {
    }

    /**
     * Test attribute "signed"
     */
    public function testPropertySigned()
    {
    }

    /**
     * Test attribute "downloaded"
     */
    public function testPropertyDownloaded()
    {
    }

    /**
     * Test attribute "signed_on"
     */
    public function testPropertySignedOn()
    {
    }

    /**
     * Test attribute "needs_to_sign"
     */
    public function testPropertyNeedsToSign()
    {
    }

    /**
     * Test attribute "approve_only"
     */
    public function testPropertyApproveOnly()
    {
    }

    /**
     * Test attribute "notify_only"
     */
    public function testPropertyNotifyOnly()
    {
    }

    /**
     * Test attribute "in_person"
     */
    public function testPropertyInPerson()
    {
    }

    /**
     * Test attribute "order"
     */
    public function testPropertyOrder()
    {
    }

    /**
     * Test attribute "language"
     */
    public function testPropertyLanguage()
    {
    }

    /**
     * Test attribute "force_language"
     */
    public function testPropertyForceLanguage()
    {
    }

    /**
     * Test attribute "emailed"
     */
    public function testPropertyEmailed()
    {
    }

    /**
     * Test attribute "verify_phone_number"
     */
    public function testPropertyVerifyPhoneNumber()
    {
    }

    /**
     * Test attribute "verify_bank_account"
     */
    public function testPropertyVerifyBankAccount()
    {
    }

    /**
     * Test attribute "declined"
     */
    public function testPropertyDeclined()
    {
    }

    /**
     * Test attribute "declined_on"
     */
    public function testPropertyDeclinedOn()
    {
    }

    /**
     * Test attribute "forwarded"
     */
    public function testPropertyForwarded()
    {
    }

    /**
     * Test attribute "forwarded_on"
     */
    public function testPropertyForwardedOn()
    {
    }

    /**
     * Test attribute "forwarded_to_email"
     */
    public function testPropertyForwardedToEmail()
    {
    }

    /**
     * Test attribute "forwarded_reason"
     */
    public function testPropertyForwardedReason()
    {
    }

    /**
     * Test attribute "message"
     */
    public function testPropertyMessage()
    {
    }

    /**
     * Test attribute "embed_url_user_id"
     */
    public function testPropertyEmbedUrlUserId()
    {
    }

    /**
     * Test attribute "inputs"
     */
    public function testPropertyInputs()
    {
    }

    /**
     * Test attribute "use_stamp_for_approve_only"
     */
    public function testPropertyUseStampForApproveOnly()
    {
    }

    /**
     * Test attribute "embed_url"
     */
    public function testPropertyEmbedUrl()
    {
    }

    /**
     * Test attribute "attachments"
     */
    public function testPropertyAttachments()
    {
    }

    /**
     * Test attribute "redirect_url"
     */
    public function testPropertyRedirectUrl()
    {
    }

    /**
     * Test attribute "redirect_url_declined"
     */
    public function testPropertyRedirectUrlDeclined()
    {
    }

    /**
     * Test attribute "after_document"
     */
    public function testPropertyAfterDocument()
    {
    }

    /**
     * Test attribute "integrations"
     */
    public function testPropertyIntegrations()
    {
    }

    /**
     * Test attribute "password"
     */
    public function testPropertyPassword()
    {
    }
}
