<?php
/**
 * DocumentsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  SignRequest
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SignRequest API
 *
 * API for SignRequest.com
 * OpenAPI spec version: v1
 * Contact: tech-support@signrequest.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace SignRequest;

use \SignRequest\Configuration;
use \SignRequest\ApiException;
use \SignRequest\ObjectSerializer;

/**
 * DocumentsApiTest Class Doc Comment
 *
 * @category Class
 * @package  SignRequest
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DocumentsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for documentsCreate
     *
     * Create a Document.
     *
     */
    public function testDocumentsCreate()
    {
    }

    /**
     * Test case for documentsDelete
     *
     * Delete a Document.
     *
     */
    public function testDocumentsDelete()
    {
    }

    /**
     * Test case for documentsList
     *
     * Retrieve a list of Documents.
     *
     */
    public function testDocumentsList()
    {
    }

    /**
     * Test case for documentsRead
     *
     * Retrieve a Document.
     *
     */
    public function testDocumentsRead()
    {
    }
}
