<?php
/**
 * TeamsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  SignRequest
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SignRequest API
 *
 * API for SignRequest.com
 * OpenAPI spec version: v1
 * Contact: tech-support@signrequest.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.11
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace SignRequest;

use \SignRequest\Configuration;
use \SignRequest\ApiException;
use \SignRequest\ObjectSerializer;

/**
 * TeamsApiTest Class Doc Comment
 *
 * @category Class
 * @package  SignRequest
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TeamsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for teamsCreate
     *
     * Create a Team.
     *
     */
    public function testTeamsCreate()
    {
    }

    /**
     * Test case for teamsDelete
     *
     * Delete a Team.
     *
     */
    public function testTeamsDelete()
    {
    }

    /**
     * Test case for teamsInviteMember
     *
     * Invite a Team Member.
     *
     */
    public function testTeamsInviteMember()
    {
    }

    /**
     * Test case for teamsList
     *
     * Retrieve a list of Teams.
     *
     */
    public function testTeamsList()
    {
    }

    /**
     * Test case for teamsPartialUpdate
     *
     * Update a Team.
     *
     */
    public function testTeamsPartialUpdate()
    {
    }

    /**
     * Test case for teamsRead
     *
     * Retrieve a Team.
     *
     */
    public function testTeamsRead()
    {
    }
}
