<?php
/**
 * WebhooksApiTest
 * PHP version 5
 *
 * @category Class
 * @package  SignRequest
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * SignRequest API
 *
 * API for SignRequest.com
 *
 * OpenAPI spec version: v1
 * Contact: tech-support@signrequest.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace SignRequest;

use \SignRequest\Configuration;
use \SignRequest\ApiException;
use \SignRequest\ObjectSerializer;

/**
 * WebhooksApiTest Class Doc Comment
 *
 * @category Class
 * @package  SignRequest
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class WebhooksApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for webhooksCreate
     *
     * Create a Webhook.
     *
     */
    public function testWebhooksCreate()
    {
    }

    /**
     * Test case for webhooksDelete
     *
     * Delete a Webhook.
     *
     */
    public function testWebhooksDelete()
    {
    }

    /**
     * Test case for webhooksList
     *
     * Retrieve a list of Webhooks.
     *
     */
    public function testWebhooksList()
    {
    }

    /**
     * Test case for webhooksPartialUpdate
     *
     * Partially update a Webhook.
     *
     */
    public function testWebhooksPartialUpdate()
    {
    }

    /**
     * Test case for webhooksRead
     *
     * Retrieve a Webhook.
     *
     */
    public function testWebhooksRead()
    {
    }

    /**
     * Test case for webhooksUpdate
     *
     * Update a Webhook.
     *
     */
    public function testWebhooksUpdate()
    {
    }
}
